name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Expo CLI
        run: pnpm add -g @expo/cli

      - name: Generate Android project
        run: npx expo prebuild --platform android --clean

      - name: Update Gradle wrapper to required version
        run: |
          cd android
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.10.2-all.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "networkTimeout=10000" >> gradle/wrapper/gradle-wrapper.properties
          echo "validateDistributionUrl=true" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "Updated gradle-wrapper.properties:"
          cat gradle/wrapper/gradle-wrapper.properties

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Verify Gradle wrapper version
        run: |
          echo "=== Gradle wrapper properties ==="
          cat gradle/wrapper/gradle-wrapper.properties
          echo "=== Gradle version check ==="
          ./gradlew --version
          echo "=== Gradle wrapper info ==="
          ./gradlew wrapper --gradle-version 8.10.2 --distribution-type all
        working-directory: android

      - name: Clean Gradle cache completely
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper
          ./gradlew clean
        working-directory: android
        continue-on-error: true

      - name: Build APK with correct Gradle version
        run: ./gradlew assembleDebug --stacktrace --info
        working-directory: android

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
