name: Build Android APK (EAS)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps
        run: npm ci

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Ensure logged in
        run: |
          # If EXPO_TOKEN is set, eas will use it automatically.
          eas whoami || echo "Using EXPO_TOKEN from env"

      - name: Start EAS Build (Android, preview profile -> APK)
        run: |
          eas build --platform android --profile preview --non-interactive
